apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    econia.service.group: dss
    io.kompose.service: processor
    release: aries
    upstream: econia
  name: processor
  namespace: econia-testnet
spec:
  replicas: 1
  selector:
    matchLabels:
      econia.service.group: dss
      io.kompose.service: processor
      release: aries
      upstream: econia
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        econia.service.group: dss
        io.kompose.network/docker-default: "true"
        io.kompose.service: processor
        release: aries
        upstream: econia
    spec:
      containers:
      - env:
        - name: HEALTHCHECK_BEFORE_START
          value: "false"
        image: 854153369854.dkr.ecr.ap-southeast-1.amazonaws.com/econia-dss/processor:latest
        imagePullPolicy: IfNotPresent
        name: processor
        ports:
        - containerPort: 8085
          hostPort: 8085
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /config/data/
          name: processor-config
      restartPolicy: Always
      volumes:
      - configMap:
          items:
          - key: config.yaml
            path: config.yaml
          name: processor-config
        name: processor-config
