apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgrest
  name: postgrest
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgrest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: postgrest
    spec:
      containers:
        - env:
            - name: PGRST_DB_ANON_ROLE
              value: web_anon
            - name: PGRST_DB_SCHEMA
              value: api
            - name: PGRST_DB_URI
              value: postgres://econia:econia@postgres:5432/econia
          image: postgrest
          imagePullPolicy: IfNotPresent
          name: postgrest
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
