apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: processor
  name: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: processor
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: processor
    spec:
      containers:
        - env:
            - name: HEALTHCHECK_BEFORE_START
              value: "false"
          image: processor
          name: processor
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
              hostPort: 8085
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /config/data/
              name: processor-config
      restartPolicy: Always
      volumes:
        - name: processor-config
          configMap:
              name: processor-config
              items:
                - key: config.yaml
                  path: config.yaml
status: {}
