apiVersion: v1
data:
  config.yaml: |-
    health_check_port: 8085
    server_config:
      processor_config:
        type: econia_transaction_processor
        econia_address: 0xc0deb00c405f84c85dc13442e305df75d1288100cdd82675695f6148c7ece51c
      postgres_connection_string: postgres://econia:econia@postgres:5432/econia
      indexer_grpc_data_service_address: https://grpc.mainnet.aptoslabs.com:443
      indexer_grpc_http2_ping_interval_in_secs: 60
      indexer_grpc_http2_ping_timeout_in_secs: 10
      number_concurrent_processing_tasks: 1
      auth_token: aptoslabs_grpc_token_or_token_for_another_grpc_endpoint
      starting_version: 154106802
kind: ConfigMap
metadata:
  name: processor-config
  namespace: econia-mainnet
