apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    econia.service.group: dss
    io.kompose.service: db
    release: aries
    upstream: econia
  name: db
  namespace: econia-mainnet
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: gp2

